import React, { useState } from 'react';
import { 
  CheckCircle2, 
  Sparkles, 
  FileText, 
  Cpu, 
  Clock, 
  Copy, 
  Check, 
  Download, 
  RotateCcw, 
  Plus, 
  Trash2, 
  ExternalLink, 
  ShieldCheck, 
  AlertTriangle, 
  Globe, 
  Search, 
  X,
  RefreshCw,
  ListTodo,
  Layers,
  ArrowRight,
  Target,
  Users
} from 'lucide-react';

export default function ResultsView({ analysisData, originalImage, userContext, onReset }) {
  const [data, setData] = useState(analysisData.data || {});
  const [copied, setCopied] = useState(false);
  const [newTaskTitle, setNewTaskTitle] = useState('');
  const [newTechName, setNewTechName] = useState('');
  const [newTechReason, setNewTechReason] = useState('');
  
  // URL Inspection state
  const [inspectingUrl, setInspectingUrl] = useState(false);
  const [websiteInspection, setWebsiteInspection] = useState(null);
  const [inspectionError, setInspectionError] = useState(null);
  const [urlDismissed, setUrlDismissed] = useState(false);

  const detectedUrl = data.detected_urls && data.detected_urls.length > 0 
    ? data.detected_urls[0] 
    : null;

  const toggleTask = (taskId) => {
    setData(prev => ({
      ...prev,
      tasks: (prev.tasks || []).map(task => {
        if (task.id === taskId) {
          const nextStatus = task.status === 'completed' ? 'pending' : 'completed';
          return { ...task, status: nextStatus };
        }
        return task;
      })
    }));
  };

  const addTask = (e) => {
    e.preventDefault();
    if (!newTaskTitle.trim()) return;
    const newTask = {
      id: `task-${Date.now()}`,
      title: newTaskTitle.trim(),
      description: 'Custom team task added in workspace',
      status: 'pending'
    };
    setData(prev => ({
      ...prev,
      tasks: [...(prev.tasks || []), newTask]
    }));
    setNewTaskTitle('');
  };

  const addTech = (e) => {
    e.preventDefault();
    if (!newTechName.trim()) return;
    setData(prev => ({
      ...prev,
      technology_stack: [
        ...(prev.technology_stack || []),
        {
          technology: newTechName.trim(),
          reason: newTechReason.trim() || 'Selected by team for implementation'
        }
      ]
    }));
    setNewTechName('');
    setNewTechReason('');
  };

  const removeTech = (indexToRemove) => {
    setData(prev => ({
      ...prev,
      technology_stack: (prev.technology_stack || []).filter((_, idx) => idx !== indexToRemove)
    }));
  };

  const handleApproveInspection = async (targetUrl) => {
    setInspectingUrl(true);
    setInspectionError(null);
    try {
      const response = await fetch('/api/inspect-url', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          url: targetUrl,
          currentPlan: data
        })
      });

      const json = await response.json();
      if (!response.ok || !json.success) {
        throw new Error(json.error || 'Failed to inspect website.');
      }

      setWebsiteInspection(json);
    } catch (err) {
      console.error('[URL INSPECT ERROR]', err.message);
      setInspectionError(err.message);
    } finally {
      setInspectingUrl(false);
    }
  };

  // Calculate task completion %
  const completedTasks = (data.tasks || []).filter(t => t.status === 'completed').length;
  const totalTasks = (data.tasks || []).length;
  const taskProgressPct = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

  // Calculate total estimated minutes
  const totalMinutes = (data.implementation_plan || []).reduce(
    (acc, step) => acc + (Number(step.estimated_minutes) || 0), 0
  );

  const generateMarkdownExport = () => {
    return `# ${data.title}
*Generated by Brief2Build AI*

## Executive Summary
${data.summary}

- **Target User:** ${data.target_user}
- **Core Problem:** ${data.problem}
${data.detected_urls && data.detected_urls.length > 0 ? `- **Detected Reference URLs:** ${data.detected_urls.join(', ')}` : ''}

---

## 1. Ground Truth Requirements (Visual Extraction)
${(data.extracted_requirements || []).map(r => `- **${r.requirement}**\n  - *Evidence Citation:* "${r.evidence}" [${r.type}]`).join('\n')}

### Constraints & Rules
${(data.constraints || []).map(c => `- ${c}`).join('\n') || '- None explicitly specified'}

### Required Deliverables
${(data.deliverables || []).map(d => `- ${d}`).join('\n') || '- Check challenge rules'}

${websiteInspection ? `
---

## 2. Live Website Inspection Findings
- **Source URL:** ${websiteInspection.source_url}
- **Status:** ${websiteInspection.retrieval_status}

### Verified Website Facts
${(websiteInspection.website_findings || []).map(f => `- **[${f.category}]** ${f.detail} *(Source: ${f.source_section || 'Official Site'})*`).join('\n')}

### Cross-Referenced Discrepancies
${(websiteInspection.conflicts_and_discrepancies || []).map(c => `- **Issue:** ${c.issue}\n  - *In Screenshot:* ${c.screenshot_version}\n  - *On Official Website:* ${c.website_version}`).join('\n') || '- No conflicts detected'}
` : ''}

---

## 3. Proposed MVP: ${data.mvp?.name || 'Project MVP'}
${data.mvp?.description || ''}

### Core MVP Features
${(data.mvp?.features || []).map(f => `- ${f}`).join('\n')}

---

## 4. Technology Stack Rationale
${(data.technology_stack || []).map(t => `- **${t.technology}**: ${t.reason}`).join('\n')}

---

## 5. Implementation Plan (~${Math.round(totalMinutes / 60)} hours total)
${(data.implementation_plan || []).map(p => `### Step ${p.step}: ${p.title} (${p.estimated_minutes} mins)\n${p.description}`).join('\n\n')}

---

## 6. Team Task Checklist
${(data.tasks || []).map(t => `- [${t.status === 'completed' ? 'x' : ' '}] **${t.title}**: ${t.description}`).join('\n')}

---

## 7. Two-Minute Judge Demo Sequence
${(data.demo_flow || []).map((step, idx) => `${idx + 1}. ${step}`).join('\n')}
`;
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdownExport();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const payload = JSON.stringify({
      brief2build_plan: data,
      website_inspection: websiteInspection,
      exported_at: new Date().toISOString()
    }, null, 2);
    
    const blob = new Blob([payload], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(data.title || 'project-plan').toLowerCase().replace(/[^a-z0-9]/g, '-')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-6xl mx-auto space-y-6">
      
      {/* Top Header Card */}
      <div className="glass-panel rounded-2xl p-6 sm:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2 mb-2.5">
            <span className="inline-flex items-center space-x-1.5 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/25 text-emerald-400 text-xs font-semibold">
              <CheckCircle2 className="h-3.5 w-3.5" />
              <span>Analysis Complete</span>
            </span>
            <span className="text-xs font-mono text-slate-400 px-2 py-0.5 rounded bg-slate-900 border border-slate-800">
              Gemma 4 Grounded
            </span>
          </div>

          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight leading-snug">
            {data.title || 'Challenge Build-Ready Plan'}
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 mt-1">
            Grounded requirements separated from AI technical recommendations. Fully interactive workspace.
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center gap-2.5 shrink-0">
          <button
            onClick={handleCopyMarkdown}
            className="px-4 py-2 rounded-xl bg-slate-800/90 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700/80 flex items-center space-x-2 transition shadow-sm"
            title="Copy as Markdown for GitHub README"
          >
            {copied ? (
              <>
                <Check className="h-4 w-4 text-emerald-400" />
                <span className="text-emerald-400">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 text-slate-400" />
                <span>Copy Markdown</span>
              </>
            )}
          </button>

          <button
            onClick={handleDownloadJSON}
            className="px-4 py-2 rounded-xl bg-slate-800/90 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700/80 flex items-center space-x-2 transition shadow-sm"
            title="Export as JSON"
          >
            <Download className="h-4 w-4 text-slate-400" />
            <span>Export JSON</span>
          </button>

          <button
            onClick={onReset}
            className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold flex items-center space-x-2 shadow-md shadow-blue-600/25 transition active:scale-[0.99]"
          >
            <RotateCcw className="h-4 w-4" />
            <span>Analyze Another</span>
          </button>
        </div>
      </div>

      {/* Provenance Legend Badges */}
      <div className="flex flex-wrap items-center gap-2.5 px-2 text-xs">
        <span className="text-slate-400 font-medium">Data Provenance:</span>
        <span className="inline-flex items-center space-x-1.5 px-2.5 py-1 rounded-lg bg-emerald-950/40 border border-emerald-800/40 text-emerald-300 font-medium">
          <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
          <span>Screenshot Ground Truth</span>
        </span>
        {websiteInspection && (
          <span className="inline-flex items-center space-x-1.5 px-2.5 py-1 rounded-lg bg-cyan-950/40 border border-cyan-800/40 text-cyan-300 font-medium">
            <span className="h-1.5 w-1.5 rounded-full bg-cyan-400" />
            <span>Live Website Findings</span>
          </span>
        )}
        <span className="inline-flex items-center space-x-1.5 px-2.5 py-1 rounded-lg bg-blue-950/40 border border-blue-800/40 text-blue-300 font-medium">
          <span className="h-1.5 w-1.5 rounded-full bg-blue-400" />
          <span>AI Recommendations</span>
        </span>
        <span className="inline-flex items-center space-x-1.5 px-2.5 py-1 rounded-lg bg-amber-950/40 border border-amber-800/40 text-amber-300 font-medium">
          <span className="h-1.5 w-1.5 rounded-full bg-amber-400" />
          <span>Needs Verification</span>
        </span>
      </div>

      {/* DETECTED URL BANNER */}
      {detectedUrl && !websiteInspection && !urlDismissed && (
        <div className="glass-panel rounded-2xl p-5 border-indigo-700/50 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-start space-x-3.5">
            <div className="p-2.5 bg-indigo-500/15 text-indigo-400 rounded-xl shrink-0 mt-0.5">
              <Globe className="h-5 w-5" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <span className="text-xs font-bold uppercase tracking-wider text-indigo-300">
                  Detected Reference Link
                </span>
              </div>
              <p className="text-xs text-slate-300 mt-1">
                Gemma 4 identified the following official reference link in your brief:
              </p>
              <div className="mt-2 flex items-center space-x-2 font-mono text-xs text-blue-300 bg-slate-950/80 px-3 py-1.5 rounded-lg border border-slate-800 max-w-lg truncate">
                <a 
                  href={detectedUrl} 
                  target="_blank" 
                  rel="noreferrer" 
                  className="truncate hover:underline flex items-center space-x-1 text-sky-300"
                >
                  <span>{detectedUrl}</span>
                  <ExternalLink className="h-3 w-3 shrink-0 inline ml-1 opacity-70" />
                </a>
              </div>
            </div>
          </div>

          <div className="flex items-center space-x-2.5 shrink-0 self-end sm:self-auto">
            <button
              type="button"
              onClick={() => setUrlDismissed(true)}
              className="px-3 py-1.5 rounded-lg text-xs text-slate-400 hover:text-slate-200 transition"
            >
              Skip
            </button>
            <button
              type="button"
              disabled={inspectingUrl}
              onClick={() => handleApproveInspection(detectedUrl)}
              className="px-4 py-2 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white text-xs font-semibold flex items-center space-x-1.5 shadow-md shadow-indigo-600/30 transition disabled:opacity-50"
            >
              {inspectingUrl ? (
                <>
                  <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                  <span>Inspecting Link...</span>
                </>
              ) : (
                <>
                  <Search className="h-3.5 w-3.5" />
                  <span>Inspect Reference Link</span>
                </>
              )}
            </button>
          </div>
        </div>
      )}

      {/* Website Inspection Results (If User Approved) */}
      {websiteInspection && (
        <div className="glass-panel rounded-2xl p-6 border-cyan-800/50 space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-cyan-800/30">
            <div className="flex items-center space-x-2 text-cyan-300 font-semibold text-sm">
              <Globe className="h-4.5 w-4.5 text-cyan-400" />
              <span>Live Website Inspection Findings</span>
            </div>
            <span className="text-[11px] font-mono text-cyan-400 bg-cyan-950/60 px-2.5 py-0.5 rounded-md border border-cyan-800/50">
              Verified Public Text
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {(websiteInspection.website_findings || []).map((find, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-slate-950/70 border border-slate-800/80">
                <span className="text-[10px] font-mono uppercase text-cyan-400 px-1.5 py-0.5 rounded bg-cyan-950/50 border border-cyan-800/40 block w-fit mb-1.5">
                  {find.category}
                </span>
                <p className="text-xs text-slate-200">{find.detail}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Main Grid: Left Column (Grounded Facts) & Right Column (Action Plan & Checklist) */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* Left Column (2 Cols Wide): Core Grounded Information */}
        <div className="lg:col-span-2 space-y-6">

          {/* Section 1: Challenge Overview */}
          <div className="glass-panel rounded-2xl p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <FileText className="h-4.5 w-4.5 text-blue-400" />
                <h2 className="text-sm font-bold uppercase tracking-wider text-slate-200">
                  Challenge Overview
                </h2>
              </div>
              <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded bg-emerald-950/70 border border-emerald-800/50 text-emerald-400 font-mono">
                Ground Truth
              </span>
            </div>
            
            <p className="text-sm text-slate-300 leading-relaxed mb-5">
              {data.summary}
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4 border-t border-slate-800/80">
              <div className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800">
                <div className="flex items-center space-x-2 text-xs font-semibold text-slate-400 mb-1.5">
                  <Users className="h-3.5 w-3.5 text-blue-400" />
                  <span>Target Beneficiary / User</span>
                </div>
                <p className="text-xs text-slate-200 leading-relaxed">{data.target_user}</p>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800">
                <div className="flex items-center space-x-2 text-xs font-semibold text-slate-400 mb-1.5">
                  <Target className="h-3.5 w-3.5 text-indigo-400" />
                  <span>Core Problem Solved</span>
                </div>
                <p className="text-xs text-slate-200 leading-relaxed">{data.problem}</p>
              </div>
            </div>
          </div>

          {/* Section 2: Key Requirements & Visual Citations */}
          <div className="glass-panel rounded-2xl p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <CheckCircle2 className="h-4.5 w-4.5 text-emerald-400" />
                <h2 className="text-sm font-bold uppercase tracking-wider text-slate-200">
                  Key Requirements & Citations ({(data.extracted_requirements || []).length})
                </h2>
              </div>
              <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded bg-emerald-950/70 border border-emerald-800/50 text-emerald-400 font-mono">
                Extracted Facts
              </span>
            </div>

            <div className="space-y-3">
              {(data.extracted_requirements || []).map((req, idx) => (
                <div key={idx} className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800/80">
                  <div className="flex items-start justify-between gap-3">
                    <p className="text-xs font-semibold text-slate-200 leading-snug">{req.requirement}</p>
                    <span className="text-[10px] uppercase font-mono px-1.5 py-0.5 rounded bg-slate-800/90 text-slate-400 shrink-0">
                      {req.type || 'explicit'}
                    </span>
                  </div>
                  {req.evidence && (
                    <div className="mt-2 text-[11px] text-slate-400 italic bg-slate-900/90 px-3 py-1.5 rounded-lg border border-slate-800/80 flex items-center space-x-1.5">
                      <span className="text-slate-500 font-mono text-[10px]">Citation:</span>
                      <span className="text-emerald-400 font-sans">"{req.evidence}"</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Section 3: Constraints & Deliverables */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            
            {/* Constraints */}
            <div className="glass-panel rounded-2xl p-5">
              <div className="flex items-center space-x-2 mb-3">
                <ShieldCheck className="h-4 w-4 text-amber-400" />
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">
                  Constraints & Rules
                </h3>
              </div>
              <ul className="space-y-2">
                {(data.constraints || []).map((c, i) => (
                  <li key={i} className="text-xs text-slate-300 flex items-start space-x-2 leading-relaxed">
                    <span className="text-amber-400 font-bold">•</span>
                    <span>{c}</span>
                  </li>
                ))}
                {(data.constraints || []).length === 0 && (
                  <li className="text-xs text-slate-500 italic">No explicit constraints noted in brief.</li>
                )}
              </ul>
            </div>

            {/* Deliverables */}
            <div className="glass-panel rounded-2xl p-5">
              <div className="flex items-center space-x-2 mb-3">
                <FileText className="h-4 w-4 text-blue-400" />
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">
                  Required Deliverables
                </h3>
              </div>
              <ul className="space-y-2">
                {(data.deliverables || []).map((d, i) => (
                  <li key={i} className="text-xs text-slate-300 flex items-start space-x-2 leading-relaxed">
                    <span className="text-blue-400 font-bold">•</span>
                    <span>{d}</span>
                  </li>
                ))}
                {(data.deliverables || []).length === 0 && (
                  <li className="text-xs text-slate-500 italic">Verify deliverables with organizers.</li>
                )}
              </ul>
            </div>

          </div>

          {/* Section 4: Editable MVP Scope */}
          <div className="glass-panel rounded-2xl p-6">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center space-x-2">
                <Sparkles className="h-4.5 w-4.5 text-indigo-400" />
                <h2 className="text-sm font-bold uppercase tracking-wider text-slate-200">
                  Suggested MVP: {data.mvp?.name || 'Project MVP'}
                </h2>
              </div>
              <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded bg-blue-950/70 border border-blue-800/50 text-blue-400 font-mono">
                AI Recommendation
              </span>
            </div>

            <textarea
              rows={2}
              value={data.mvp?.description || ''}
              onChange={(e) => setData(prev => ({
                ...prev,
                mvp: { ...prev.mvp, description: e.target.value }
              }))}
              className="w-full bg-slate-950/80 border border-slate-800 rounded-xl p-3 text-xs text-slate-200 mb-4 focus:ring-1 focus:ring-blue-500 outline-none leading-relaxed"
              placeholder="Edit MVP scope..."
            />

            <span className="text-xs font-semibold text-slate-400 block mb-2">Core MVP Features:</span>
            <div className="space-y-2">
              {(data.mvp?.features || []).map((feat, idx) => (
                <div key={idx} className="flex items-center space-x-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-indigo-400 shrink-0" />
                  <input
                    type="text"
                    value={feat}
                    onChange={(e) => {
                      const updated = [...(data.mvp?.features || [])];
                      updated[idx] = e.target.value;
                      setData(prev => ({
                        ...prev,
                        mvp: { ...prev.mvp, features: updated }
                      }));
                    }}
                    className="flex-1 bg-slate-950/80 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:ring-1 focus:ring-blue-500 outline-none"
                  />
                </div>
              ))}
            </div>
          </div>

          {/* Section 5: Recommended Technology Stack */}
          <div className="glass-panel rounded-2xl p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <Cpu className="h-4.5 w-4.5 text-blue-400" />
                <h2 className="text-sm font-bold uppercase tracking-wider text-slate-200">
                  Recommended Technology Stack ({(data.technology_stack || []).length})
                </h2>
              </div>
              <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded bg-blue-950/70 border border-blue-800/50 text-blue-400 font-mono">
                AI Recommendation
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
              {(data.technology_stack || []).map((item, idx) => (
                <div key={idx} className="p-3 bg-slate-950/70 rounded-xl border border-slate-800/80 relative group">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-white">{item.technology}</span>
                    <button
                      type="button"
                      onClick={() => removeTech(idx)}
                      className="text-slate-500 hover:text-red-400 p-1 opacity-0 group-hover:opacity-100 transition"
                      title="Remove technology"
                    >
                      <Trash2 className="h-3 w-3" />
                    </button>
                  </div>
                  <p className="text-[11px] text-slate-400 mt-1 leading-snug">{item.reason}</p>
                </div>
              ))}
            </div>

            {/* Add Custom Tech Form */}
            <form onSubmit={addTech} className="flex flex-col sm:flex-row items-center gap-2 pt-3 border-t border-slate-800/80">
              <input
                type="text"
                value={newTechName}
                onChange={(e) => setNewTechName(e.target.value)}
                placeholder="Add tool/library..."
                className="flex-1 w-full sm:w-auto bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
              <input
                type="text"
                value={newTechReason}
                onChange={(e) => setNewTechReason(e.target.value)}
                placeholder="Reason..."
                className="flex-1 w-full sm:w-auto bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
              <button
                type="submit"
                disabled={!newTechName.trim()}
                className="w-full sm:w-auto px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold flex items-center justify-center space-x-1 transition disabled:opacity-40"
              >
                <Plus className="h-3.5 w-3.5" />
                <span>Add</span>
              </button>
            </form>
          </div>

          {/* Section 6: Development Roadmap */}
          <div className="glass-panel rounded-2xl p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <Clock className="h-4.5 w-4.5 text-indigo-400" />
                <h2 className="text-sm font-bold uppercase tracking-wider text-slate-200">
                  Development Roadmap (~{Math.round(totalMinutes / 60)}h Total)
                </h2>
              </div>
              <span className="text-[10px] font-semibold uppercase px-2 py-0.5 rounded bg-blue-950/70 border border-blue-800/50 text-blue-400 font-mono">
                Structured Phases
              </span>
            </div>

            <div className="space-y-3">
              {(data.implementation_plan || []).map((step, idx) => (
                <div key={idx} className="p-3.5 bg-slate-950/70 rounded-xl border border-slate-800/80 flex items-start space-x-3.5">
                  <div className="h-6 w-6 rounded-lg bg-blue-500/10 border border-blue-500/20 text-blue-400 flex items-center justify-center text-xs font-bold shrink-0 mt-0.5">
                    {step.step || idx + 1}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                      <h3 className="text-xs font-bold text-slate-200">{step.title}</h3>
                      <span className="text-[10px] font-mono text-slate-400 bg-slate-900 px-2 py-0.5 rounded border border-slate-800 w-fit">
                        ~{step.estimated_minutes} mins
                      </span>
                    </div>
                    <p className="text-xs text-slate-400 mt-1 leading-relaxed">{step.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Right Column (1 Col Wide): Interactive Checklist & Demo Pitch Flow */}
        <div className="space-y-6">

          {/* Interactive Team Checklist */}
          <div className="glass-panel rounded-2xl p-6 space-y-4 sticky top-20">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800/80">
              <div className="flex items-center space-x-2">
                <ListTodo className="h-4.5 w-4.5 text-emerald-400" />
                <h2 className="text-sm font-bold text-slate-200 uppercase tracking-wider">
                  Team Checklist
                </h2>
              </div>
              <span className="text-xs font-mono text-emerald-400 bg-emerald-950/60 px-2 py-0.5 rounded border border-emerald-800/50">
                {completedTasks}/{totalTasks} Done
              </span>
            </div>

            {/* Progress Bar */}
            <div>
              <div className="flex justify-between text-[11px] text-slate-400 mb-1 font-mono">
                <span>Completion</span>
                <span>{taskProgressPct}%</span>
              </div>
              <div className="h-2 w-full bg-slate-950 rounded-full overflow-hidden border border-slate-800">
                <div 
                  className="h-full bg-gradient-to-r from-blue-500 to-emerald-400 transition-all duration-300 rounded-full"
                  style={{ width: `${taskProgressPct}%` }}
                />
              </div>
            </div>

            {/* Checklist Items */}
            <div className="space-y-2 max-h-[380px] overflow-y-auto pr-1">
              {(data.tasks || []).map((task) => (
                <div 
                  key={task.id}
                  onClick={() => toggleTask(task.id)}
                  className={`p-3 rounded-xl border text-xs cursor-pointer transition-all flex items-start space-x-2.5 ${
                    task.status === 'completed'
                      ? 'bg-emerald-950/20 border-emerald-800/40 text-slate-400 line-through'
                      : 'bg-slate-950/70 border-slate-800 text-slate-200 hover:border-slate-700'
                  }`}
                >
                  <input
                    type="checkbox"
                    checked={task.status === 'completed'}
                    onChange={() => {}} // handled by parent onClick
                    className="mt-0.5 rounded border-slate-700 text-emerald-500 focus:ring-0 shrink-0 cursor-pointer"
                  />
                  <div className="flex-1 min-w-0">
                    <p className={`font-semibold ${task.status === 'completed' ? 'text-slate-400' : 'text-slate-200'}`}>
                      {task.title}
                    </p>
                    {task.description && (
                      <p className="text-[11px] text-slate-400 mt-0.5 no-underline">
                        {task.description}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>

            {/* Add Custom Task Form */}
            <form onSubmit={addTask} className="pt-3 border-t border-slate-800/80 flex items-center space-x-2">
              <input
                type="text"
                value={newTaskTitle}
                onChange={(e) => setNewTaskTitle(e.target.value)}
                placeholder="Add custom task..."
                className="flex-1 bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
              <button
                type="submit"
                disabled={!newTaskTitle.trim()}
                className="px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold flex items-center space-x-1 transition disabled:opacity-40"
              >
                <Plus className="h-3.5 w-3.5" />
                <span>Add</span>
              </button>
            </form>
          </div>

          {/* Section 7: 2-Minute Demo Pitch Flow */}
          <div className="glass-panel rounded-2xl p-6">
            <div className="flex items-center space-x-2 mb-3">
              <Sparkles className="h-4.5 w-4.5 text-amber-400" />
              <h2 className="text-sm font-bold uppercase tracking-wider text-slate-200">
                2-Minute Demo Flow
              </h2>
            </div>
            <div className="space-y-2.5">
              {(data.demo_flow || []).map((flow, i) => (
                <div key={i} className="p-3 bg-slate-950/70 rounded-xl border border-slate-800/80 text-xs">
                  <span className="font-mono text-amber-300 font-bold mr-1.5">{i + 1}.</span>
                  <span className="text-slate-300 leading-snug">{flow}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Section 8: Uncertainties & Ambiguities to Verify */}
          {(data.uncertainties || []).length > 0 && (
            <div className="glass-panel rounded-2xl p-6 border-amber-800/40">
              <div className="flex items-center space-x-2 text-amber-400 mb-3">
                <AlertTriangle className="h-4.5 w-4.5" />
                <h2 className="text-sm font-bold uppercase tracking-wider">
                  Uncertainties to Verify
                </h2>
              </div>
              <ul className="space-y-2">
                {(data.uncertainties || []).map((u, i) => (
                  <li key={i} className="text-xs text-amber-200/90 flex items-start space-x-2 leading-relaxed">
                    <span className="text-amber-400 font-bold">•</span>
                    <span>{u}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

        </div>

      </div>

    </div>
  );
}
